<?xml version="1.0" encoding="utf-8"?><Database Name="KarateSchool(1)" Class="KarateSchoolDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Instructor" Member="Instructors">
    <Type Name="Instructor">
      <Column Name="InstructorID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InstructorFirstName" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="InstructorLastName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="InstructorPhoneNumber" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Member" Member="Members">
    <Type Name="Member">
      <Column Name="Member_UserID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MemberFirstName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="MemberLastName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="MemberDateJoined" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MemberPhoneNumber" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="MemberEmail" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>